version: '3.8'

services:
  taches-menageres:
    build: .
    container_name: taches-menageres
    ports:
      - "3001:3001"
    volumes:
      # Persistance des données
      - ./data:/app/server/data
      # Logs
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - taches-network

networks:
  taches-network:
    driver: bridge 